config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/jcs', as: 'rails_admin'
  resources :items
  devise_for :admins
  resources :providers
  resources :dispatches
  resources :biddings
  resources :clients

  root to: "rails_admin/main#dashboard"
end

app/models/bidding.rb
class Bidding < ApplicationRecord
  belongs_to :client
  has_many :dispatches

  STATUS = ['Proxima', 'Realizada', 'Cobrada']

  validates_presence_of :code, :provision_order, :client_id, :dispatches
  validates_inclusion_of :status, in: ->(bidding) { STATUS }

  def rails_admin_status_enum
    STATUS
  end
end

app/controllers/biddings_controller.rb
class BiddingsController < ApplicationController
  before_action :set_bidding, only: [:show, :edit, :update, :destroy]

  # GET /biddings
  # GET /biddings.json
  def index
    @biddings = Bidding.all
  end

  # GET /biddings/1
  # GET /biddings/1.json
  def show
  end

  # GET /biddings/new
  def new
    @bidding = Bidding.new
  end

  # GET /biddings/1/edit
  def edit
  end

  # POST /biddings
  # POST /biddings.json
  def create
    @bidding = Bidding.new(bidding_params)

    respond_to do |format|
      if @bidding.save
        format.html { redirect_to @bidding, notice: 'Bidding was successfully created.' }
        format.json { render :show, status: :created, location: @bidding }
      else
        format.html { render :new }
        format.json { render json: @bidding.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /biddings/1
  # PATCH/PUT /biddings/1.json
  def update
    respond_to do |format|
      if @bidding.update(bidding_params)
        format.html { redirect_to @bidding, notice: 'Bidding was successfully updated.' }
        format.json { render :show, status: :ok, location: @bidding }
      else
        format.html { render :edit }
        format.json { render json: @bidding.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /biddings/1
  # DELETE /biddings/1.json
  def destroy
    @bidding.destroy
    respond_to do |format|
      format.html { redirect_to biddings_url, notice: 'Bidding was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bidding
      @bidding = Bidding.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bidding_params
      params.require(:bidding).permit(:code, :provision_order, :status)
    end
end

app/helpers/biddings_helper.rb
module BiddingsHelper
end

app/views/biddings/_form.html.erb
<%= form_for(bidding) do |f| %>
  <% if bidding.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bidding.errors.count, "error") %> prohibited this bidding from being saved:</h2>

      <ul>
      <% bidding.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %>
    <%= f.text_field :code %>
  </div>

  <div class="field">
    <%= f.label :provision_order %>
    <%= f.text_field :provision_order %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/biddings/edit.html.erb
<h1>Editing Bidding</h1>

<%= render 'form', bidding: @bidding %>

<%= link_to 'Show', @bidding %> |
<%= link_to 'Back', biddings_path %>

app/views/biddings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Biddings</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Provision order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @biddings.each do |bidding| %>
      <tr>
        <td><%= bidding.code %></td>
        <td><%= bidding.provision_order %></td>
        <td><%= link_to 'Show', bidding %></td>
        <td><%= link_to 'Edit', edit_bidding_path(bidding) %></td>
        <td><%= link_to 'Destroy', bidding, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bidding', new_bidding_path %>

app/views/biddings/new.html.erb
<h1>New Bidding</h1>

<%= render 'form', bidding: @bidding %>

<%= link_to 'Back', biddings_path %>

app/views/biddings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @bidding.code %>
</p>

<p>
  <strong>Provision order:</strong>
  <%= @bidding.provision_order %>
</p>

<%= link_to 'Edit', edit_bidding_path(@bidding) %> |
<%= link_to 'Back', biddings_path %>